### ISSUE TITLE
Embedded MongoDB의 버전을 수정한다.

### ISSUE THREAD

**Issue by KIMSEI1124** [What-s-Your-Plan/wypl-backend#34]
## 📑 개요

현재 Embedded MongoDB `de.flapdoodle.embed:de.flapdoodle.embed.mongo.spring31x:4.11.0`을 사용하고 있는데 여러가지의 취약점이 있다고 경고가 발생하였습니다.

![2024-09-30_10-28-46](https://github.com/user-attachments/assets/bc6cf6de-61fd-4508-8052-2b3152dcfabf)

이를 해결하기 위해 현재 최신버전인 `de.flapdoodle.embed:de.flapdoodle.embed.mongo.spring3x:4.16.1` 을 사용합니다.

```yml
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5
```        

yml 파일도 다음과 같이 `4.0.2` 버전에서 `5.0.5` 버전으로 업그레이드 합니다.

### 🚀 상세 작업 내용

---

- build.gradle 수정
- [yml](https://github.com/What-s-Your-Plan/wypl-server-properties) 파일 수정

### ⏰ 예상 소요 시간

---

10분

### 📁 ETC

---
